# GitHub Pages Deployment

name: GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js v18
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm run build
    - run: npm run ci
    - name: Upload to Pages
      uses: actions/upload-pages-artifact@v1.0.7
      with:
        path: dist
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.4
