# GitHub Pages Deployment

name: GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ng-easy/npm-install@v2
    - run: npm run build
    - run: npm run test
    - name: Upload to Pages
      uses: actions/upload-pages-artifact@v1.0.7
      with:
        path: dist
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.4
